current_version = "0.6.0"

[[files]]
path = "pyproject.toml"

search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""


[[files]]
path = "src/deck2pdf/__init__.py"

search = "__version__ = \"{{current_version}}\""
replace = "__version__ = \"{{new_version}}\""


[[files]]
path = "CHANGES.rst"

search = """
Change logs
===========
"""
replace = """
Change logs
===========

v{{new_version}}
={% for _ in new_version %}={% endfor %}

:Date: {{ now|date }} (JST)

Breaking changes
----------------

Features
--------

Fixes
-----

Others
------
"""

