version: 2

build:
  os: 'ubuntu-22.04'
  tools:
    rust: 'latest'
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --frozen
    - uv run sphinx-build -b dirhtml docs $READTHEDOCS_OUTPUT/html

# Optionally build your docs in additional formats such as PDF and ePub
formats: []
