version: '3'

vars:
  # If you run bare environment or activated venv, set '' (blank string)
  RUN_PYTHON: 'uv run'

tasks:
  setup:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --frozen'
      - 'uv run playwright install chromium'
  verify:
    desc: 'Verify healthy of local workspace'
    cmds:
      - 'uvx pre-commit run --all-files'
      - 'uv run pytest'
      - task: 'docs:intl'
      - task: 'docs:build-linkcheck'
      - task: 'docs:build-dirhtml'
      - 'uv build'
  release-*:
    desc: 'Run release process'
    vars:
      LEVEL: '{{index .MATCH 0}}'
    cmds:
      - 'age {{.LEVEL}}'
      - 'uv sync'  # To write out as lock-file

includes:
  docs: './docs'
